


# Permalinks
permalink:        pretty

# Setup
title:            Holy Cross Manuscripts Hackathon
tagline:          'February 2, 2019'
description:      'One-day collaborative hackathon to produce a digital diplomatic edition of a 9th-century manuscript of the *Aratea* of Germanicus Caesar (Basel, Universitätsbibliothek, AN IV 18).'


baseurl: '/ms-hackathon-2019/'


author:
  name:           'Neel Smith'


links:
  - title: HC MID club
    url: http://hcmid.github.io/
    external: true
